// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDroygvB1pp7hLaOfcBClaw73eJ4syPrmk',
    appId: '1:852951479768:web:57bcf90ae633adcce06ead',
    messagingSenderId: '852951479768',
    projectId: 'coffee-shop-164db',
    authDomain: 'coffee-shop-164db.firebaseapp.com',
    storageBucket: 'coffee-shop-164db.appspot.com',
    measurementId: 'G-2SB16DSX9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHWATg1r2pg9gOn5FVsVD_TZOC7Qb0JT8',
    appId: '1:852951479768:android:196b4d748fc9ee00e06ead',
    messagingSenderId: '852951479768',
    projectId: 'coffee-shop-164db',
    storageBucket: 'coffee-shop-164db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq7y_N7uB2HcS-xJn5IExaUkY1_CVSDw4',
    appId: '1:852951479768:ios:1f13b5dc28623053e06ead',
    messagingSenderId: '852951479768',
    projectId: 'coffee-shop-164db',
    storageBucket: 'coffee-shop-164db.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq7y_N7uB2HcS-xJn5IExaUkY1_CVSDw4',
    appId: '1:852951479768:ios:1f13b5dc28623053e06ead',
    messagingSenderId: '852951479768',
    projectId: 'coffee-shop-164db',
    storageBucket: 'coffee-shop-164db.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDroygvB1pp7hLaOfcBClaw73eJ4syPrmk',
    appId: '1:852951479768:web:72f3880b6a5efb7be06ead',
    messagingSenderId: '852951479768',
    projectId: 'coffee-shop-164db',
    authDomain: 'coffee-shop-164db.firebaseapp.com',
    storageBucket: 'coffee-shop-164db.appspot.com',
    measurementId: 'G-9CQBZ9GC0S',
  );

}